# .golangci.yml
run:
  timeout: 10m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - deadcode
    - gocritic
    - gocyclo
    - misspell
    - gofmt
    - goimports
    - golint
    - varcheck
    - structcheck
    - unused
    - unparam
    - typecheck
    - nakedret
    - prealloc

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
