services:
  app:
    container_name: appliance_surge_app
    build: .
    environment:
      DATABASE_URL: 'postgres://postgres:postgres@appliance_surge_db:5432/postgres?sslmode=disable'
      PORT: 8080
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    container_name: appliance_surge_db
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
